name: wireguard_flutter
description: A wire-guard flutter vpn project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  # wireguard_vpn: ^0.0.1+3
  responsive_builder: ^0.7.0
  awesome_notifications: ^0.7.4+1
  get: ^4.6.5
  get_storage: ^2.1.1
  #flutter_svg_provider: ^1.0.3
  dio: ^5.1.2
  google_fonts: ^5.0.0
  dotted_line: ^3.1.0
  #flutter_statusbarcolor_ns: ^0.5.0
#  flutter_form_builder: ^9.0.0
#  form_builder_validators: ^9.0.0
  # connectivity_plus: ^3.0.6
  fade_shimmer: ^2.2.0
  intl: ^0.18.1
  flutter_advanced_switch: ^3.0.1
  flutter_easyloading: ^3.0.5
  flutter_icons:
    git:
      url: https://github.com/Sayed-Siam123/flutter-icons-master.git
      ref: master

  adaptive_theme: ^3.3.0
  loggy: ^2.0.3
  #url_launcher: ^6.1.10
  flutter_screenutil: ^5.8.4
  path_provider: ^2.0.15
  video_player: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_automation: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_app_name: ^0.1.1
  flutter_lints: ^2.0.1

dependency_overrides:
  http: ^1.0.0
  xml: ^6.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 24
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"

flutter_app_name:
  name: "Echo"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/logo/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
